name: Continous Integration

on:
  push:
    branches:
      - main
      - test-branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git
      uses: actions/checkout@v4

    - name: Instalar dependencias
      run: |
        npm install

    - name: Pruebas Jest
      run: |
        npm run test

    - name: Pruebas Cypress
      run: |
        echo "Corriendo pruebas Cypress..."
        echo "Pruebas incorrectas! Todo mal!"
        echo "No tienes instalado Cypress! Tonto!"
        exit 70
